### ISSUE TITLE
Use some base58 (or base56) encoding instead of base64?

### ISSUE THREAD

**Issue by rxcomm** [tych0/pw#2]
Some applications don't allow non alphanumeric characters in the password. Perhaps use some base58 or base56 encoding to handle this case. Then add the special characters.

**Comment by tych0** [comment]
On Mon, Dec 04, 2017 at 06:03:41PM +0000, rxcomm wrote:
> Some applications don't allow non alphanumeric characters in the password. Perhaps use some base58 or base56 encoding to handle this case. Then add the special characters.

Yeah, this is probably a good idea, especially since people can inject
their own special character set anyways.

Thanks!

**Comment by tych0** [comment]
This is fixed by https://github.com/tych0/pw/commit/770a771fb0b5f3b22d6683d21927e0fcd70467a8
